export const industryTemplates = [
  {
    id: "beauty-salon",
    name: "Gözəllik Salonu / Beauty Salon",
    services: "Saç kəsimi - 15 AZN\nSaç boyası - 30 AZN\nManikür - 12 AZN\nPedikür - 15 AZN\nQaş dizaynı - 8 AZN\nMakiyaj - 25 AZN\nSaç düzəltmə - 20 AZN",
    pricing: "Qiymətlər xidmətdən asılıdır. Əlavə xidmətlər üçün zəng edin.",
  },
  {
    id: "barbershop",
    name: "Bərbərxana / Barbershop",
    services: "Saç kəsimi - 10 AZN\nSaqqal düzəltmə - 8 AZN\nSaç + Saqqal - 15 AZN\nUşaq saç kəsimi - 7 AZN\nSaç yuma + stil - 12 AZN\nQısa kəsim (maşınla) - 8 AZN",
    pricing: "Sabit qiymətlər. Qrup endirimləri mövcuddur.",
  },
  {
    id: "restaurant",
    name: "Restoran / Restaurant",
    services: "Səhər yeməyi - 8-15 AZN\nBiznes lanç - 12 AZN\nŞam yeməyi - 15-40 AZN\nDesert - 5-10 AZN\nİçkilər - 3-8 AZN\nCatering xidməti - razılaşma ilə",
    pricing: "Menyu qiymətləri. Böyük sifarişlərə endirim. Catering üçün əlaqə saxlayın.",
  },
  {
    id: "cafe",
    name: "Kafe / Cafe",
    services: "Espresso - 3 AZN\nKapuçino - 5 AZN\nLatte - 5 AZN\nÇay - 2 AZN\nDesertlər - 4-8 AZN\nSendviçlər - 6-10 AZN\nSmoothie - 7 AZN",
    pricing: "Daimi müştərilərə 10% endirim kartı. Take-away mövcuddur.",
  },
  {
    id: "dental-clinic",
    name: "Diş Klinikası / Dental Clinic",
    services: "Müayinə - 20 AZN\nDiş təmizləmə - 40 AZN\nDolğu - 30-60 AZN\nDiş çıxarma - 25-50 AZN\nAğardma - 80 AZN\nİmplant - 500-800 AZN\nBreket sistemi - 800-1500 AZN",
    pricing: "İlk müayinə pulsuzdur. Hissə-hissə ödəniş mümkündür.",
  },
  {
    id: "medical-clinic",
    name: "Tibb Klinikası / Medical Clinic",
    services: "Ümumi müayinə - 30 AZN\nQan analizi - 15-40 AZN\nUZİ - 25 AZN\nEKQ - 20 AZN\nMüalicə planı - 50 AZN\nVaksinasiya - 15-30 AZN",
    pricing: "Sığorta qəbul olunur. Konsultasiya 30 dəqiqə daxildir.",
  },
  {
    id: "pharmacy",
    name: "Aptek / Pharmacy",
    services: "Reseptli dərmanlar\nReseptsiz dərmanlar\nVitaminlər və əlavələr\nTibbi avadanlıq\nKosmetika\nUşaq qidası\nÇatdırılma xidməti",
    pricing: "Bazar qiymətləri. Çatdırılma 3 AZN (50 AZN-dən yuxarı pulsuz).",
  },
  {
    id: "gym-fitness",
    name: "İdman Zalı / Gym & Fitness",
    services: "Aylıq abunə - 40 AZN\n3 aylıq abunə - 100 AZN\nŞəxsi məşqçi - 25 AZN/saat\nQrup məşqləri - 10 AZN\nYoqa - 12 AZN\nPilates - 12 AZN\nBoks - 15 AZN",
    pricing: "İlk məşq pulsuzdur. Ailə endirimləri mövcuddur.",
  },
  {
    id: "auto-service",
    name: "Avtoservis / Auto Service",
    services: "Yağ dəyişmə - 30 AZN\nBalans - 20 AZN\nTəkər dəyişmə - 15 AZN\nDiaqnostika - 25 AZN\nTormoz sistemi - 40-80 AZN\nMühərrik təmiri - razılaşma ilə\nBoya işləri - razılaşma ilə",
    pricing: "Diaqnostika pulsuzdur. Ehtiyat hissələri ayrıca.",
  },
  {
    id: "car-wash",
    name: "Avtomoyka / Car Wash",
    services: "Xarici yuma - 8 AZN\nDaxili təmizlik - 12 AZN\nKompleks yuma - 18 AZN\nPolirovka - 40 AZN\nSalon dezinfeksiya - 15 AZN\nMühərrik yuma - 10 AZN",
    pricing: "Abunə kartı: 10 yuma = 1 pulsuz. SUV üçün +3 AZN.",
  },
  {
    id: "real-estate",
    name: "Daşınmaz Əmlak / Real Estate",
    services: "Mənzil satışı\nMənzil kirayəsi\nOfis kirayəsi\nTicarət sahəsi\nTorpaq satışı\nQiymətləndirmə xidməti\nHüquqi dəstək",
    pricing: "Komissiya: satışda 2%, kirayədə 1 aylıq. Qiymətləndirmə 100 AZN.",
  },
  {
    id: "lawyer",
    name: "Hüquqşünas / Lawyer",
    services: "Hüquqi konsultasiya - 50 AZN\nMüqavilə hazırlanması - 100 AZN\nMəhkəmə təmsilçiliyi - razılaşma ilə\nŞirkət qeydiyyatı - 200 AZN\nVergi konsultasiyası - 80 AZN\nMülkiyyət məsələləri - razılaşma ilə",
    pricing: "İlk konsultasiya 30 dəqiqə pulsuzdur. Paket endirimlər mövcuddur.",
  },
  {
    id: "accounting",
    name: "Mühasibatlıq / Accounting",
    services: "Aylıq mühasibatlıq - 100-300 AZN\nVergi bəyannaməsi - 50 AZN\nMaliyyə hesabatı - 80 AZN\nAudit - razılaşma ilə\nŞirkət qeydiyyatı - 150 AZN\nƏDV hesabatı - 40 AZN",
    pricing: "Aylıq abunə sistemi. Kiçik biznes üçün xüsusi paketlər.",
  },
  {
    id: "photography",
    name: "Fotoqraf / Photography",
    services: "Portret çəkiliş - 50 AZN\nToy çəkilişi - 300-800 AZN\nMəhsul fotosu - 10 AZN/ədəd\nTədbirlər - 200 AZN\nUşaq çəkilişi - 80 AZN\nVideo çəkiliş - 150 AZN/saat",
    pricing: "Paketlər mövcuddur. Təcili sifariş +30%. Onlayn albom daxildir.",
  },
  {
    id: "education",
    name: "Təhsil Mərkəzi / Education Center",
    services: "İngilis dili - 60 AZN/ay\nRus dili - 50 AZN/ay\nRiyaziyyat - 50 AZN/ay\nProqramlaşdırma - 80 AZN/ay\nAbitüriyent hazırlığı - 70 AZN/ay\nUşaq inkişafı - 40 AZN/ay",
    pricing: "Qruplar 5-8 nəfər. Fərdi dərslər +50%. İlk dərs sınaq (pulsuz).",
  },
  {
    id: "it-services",
    name: "IT Xidmətləri / IT Services",
    services: "Veb sayt hazırlanması - 500-2000 AZN\nMobil tətbiq - 1000-5000 AZN\nSMM xidməti - 200 AZN/ay\nSEO optimizasiya - 150 AZN/ay\nTexniki dəstək - 100 AZN/ay\nServer quraşdırma - razılaşma ilə",
    pricing: "Layihə əsaslı və ya aylıq ödəniş. Pulsuz texniki müzakirə.",
  },
  {
    id: "cleaning",
    name: "Təmizlik Xidməti / Cleaning Service",
    services: "Ev təmizliyi - 40 AZN\nOfis təmizliyi - 60 AZN\nTəmir sonrası təmizlik - 80 AZN\nPəncərə yuma - 5 AZN/ədəd\nXalça yuma - 3 AZN/m²\nDivan təmizliyi - 25 AZN",
    pricing: "Müntəzəm müştərilərə 15% endirim. Çatdırılma pulsuzdur.",
  },
  {
    id: "flower-shop",
    name: "Gül Mağazası / Flower Shop",
    services: "Buket - 20-100 AZN\nToy bəzəyi - razılaşma ilə\nOfis çiçəkləri - 15 AZN/ay\nTədbir dekorasiyası - razılaşma ilə\nÇatdırılma - 5 AZN\nKorporativ sifarişlər",
    pricing: "Bayramlarda əvvəlcədən sifariş tövsiyə olunur. 50 AZN+ pulsuz çatdırılma.",
  },
  {
    id: "pet-shop",
    name: "Heyvan Mağazası / Pet Shop",
    services: "Heyvan yeməkləri\nAksessuarlar\nBaytarlıq məsləhəti - 15 AZN\nHeyvan baxımı (grooming) - 20-40 AZN\nAkvarium xidməti - 30 AZN\nÇatdırılma xidməti",
    pricing: "Sadiq müştəri kartı: hər 10 alışda 1 pulsuz. Çatdırılma 3 AZN.",
  },
  {
    id: "travel-agency",
    name: "Turizm Agentliyi / Travel Agency",
    services: "Tur paketləri\nOtel rezervasiyası\nAviabilet\nViza xidməti - 30 AZN\nTransfer xidməti\nSığorta - 20 AZN\nKorporativ turlat",
    pricing: "Erkən rezervasiya 10-20% endirim. Qrup turlarına xüsusi qiymət.",
  },
  {
    id: "construction",
    name: "Tikinti / Construction",
    services: "Təmir işləri - razılaşma ilə\nDizayn layihəsi - 200-500 AZN\nSantexnika - 50 AZN/saat\nElektrik işləri - 40 AZN/saat\nBoya işləri - 5 AZN/m²\nDöşəmə - 8 AZN/m²",
    pricing: "Pulsuz ölçü və hesablama. Material daxil deyil (ayrıca).",
  },
  {
    id: "tailor",
    name: "Dərzi / Tailor",
    services: "Kostyum tikişi - 150-400 AZN\nDon tikişi - 80-200 AZN\nDəyişiklik (qısaltma) - 10 AZN\nFermuarr dəyişmə - 8 AZN\nDüymə tikişi - 3 AZN\nPərdə tikişi - razılaşma ilə",
    pricing: "Parça daxil deyil. Təcili sifariş +50%. Pulsuz ölçü götürmə.",
  },
  {
    id: "logistics",
    name: "Logistika / Logistics",
    services: "Şəhərdaxili çatdırılma - 5-15 AZN\nŞəhərlərarası daşıma - razılaşma ilə\nAnbar xidməti - 50 AZN/ay\nGömrük xidməti\nKuryer xidməti - 3 AZN\nKorporativ logistika",
    pricing: "Həcm və məsafəyə görə. Müntəzəm müştərilərə xüsusi tarifnər.",
  },
  {
    id: "printing",
    name: "Çap Xidməti / Printing",
    services: "Vizit kartı (100 ədəd) - 15 AZN\nBanner - 8 AZN/m²\nBuklet - 0.5 AZN/ədəd\nStiker - 0.3 AZN/ədəd\nFoto çap - 0.5 AZN\nBrend dizayn - 100 AZN\nQablaşdırma dizaynı - razılaşma ilə",
    pricing: "Böyük tirajlarda endirim. Təcili çap +30%. Dizayn daxildir.",
  },
];
